#!/usr/bin/env bash
# Install the toolkit into Exegol's my-resources so every container - present and
# future - has all eight commands on $PATH with no pip step and no network.
#
# The tools share a package now, so a bare file copy into bin/ wouldn't find its
# imports. Instead this drops the package next to bin/ and writes one small
# launcher per command that puts it on sys.path first. Same result as before:
# real files in bin/, instant, offline, nothing to install inside the container.
#
#   ./install-exegol.sh              # default ~/.exegol/my-resources/bin
#   ./install-exegol.sh /some/other/bin
set -euo pipefail

BIN_DIR="${1:-$HOME/.exegol/my-resources/bin}"
PKG_DIR="$BIN_DIR/.oscp-toolkit"
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/src"

COMMANDS=(
  "nmap-recon:nmap_recon:main_cli"
  "http-serve:http_serve:main_cli"
  "ad-enum:ad_enum:main_cli"
  "hash-triage:hash_triage:main_cli"
  "bh-quickwin:bh_quickwin:main_cli"
  "ligolo-pivot:ligolo_pivot:main_cli"
  "script-logger:script_logger:main_cli"
  "mark:script_logger:main_mark_cli"
)

if [[ ! -d "$SRC_DIR/oscp_toolkit" ]]; then
  echo "error: can't find the package at $SRC_DIR/oscp_toolkit" >&2
  exit 1
fi

mkdir -p "$BIN_DIR"
rm -rf "$PKG_DIR"
mkdir -p "$PKG_DIR"
cp -R "$SRC_DIR/oscp_toolkit" "$PKG_DIR/"
find "$PKG_DIR" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

for entry in "${COMMANDS[@]}"; do
  IFS=: read -r cmd module func <<< "$entry"
  # Remove first. If the target is a symlink (an older install had `mark` symlinked
  # to script_logger.py), `cat >` follows it and overwrites the FILE IT POINTS AT
  # instead of replacing the link. rm on a symlink removes the link, not the target.
  rm -f "$BIN_DIR/$cmd"
  cat > "$BIN_DIR/$cmd" <<LAUNCHER
#!/usr/bin/env python3
# Generated by install-exegol.sh - edit the package, not this file.
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), ".oscp-toolkit"))
from oscp_toolkit.$module import $func

sys.exit($func())
LAUNCHER
  chmod +x "$BIN_DIR/$cmd"
done

echo "Installed into $BIN_DIR"
printf '  %s\n' "${COMMANDS[@]%%:*}"
echo
echo "my-resources is a live bind mount, so this is available in running containers now."
echo "Optional, for nicer output:  pip install rich defusedxml"
